---
- hosts: "{{ passed_in_hosts }}"
  become: yes
  remote_user: ec2-user
  become_user: root
  tasks:
    - name: install httpd
      yum:
        pkg: httpd
        state: latest
    - name: Start and Enable Apache
      service:
        name: httpd
        enabled: yes
      notify: start apache
  handlers:
    - name: start apache
      service: name=httpd state=started
